
from accor_cli import  accor_cli as accor
from accum_cli import  accum_cli as accum
from apparentsens_cli import  apparentsens_cli as apparentsens
from applycal_cli import  applycal_cli as applycal
from asdmsummary_cli import  asdmsummary_cli as asdmsummary
from bandpass_cli import  bandpass_cli as bandpass
from blcal_cli import  blcal_cli as blcal
from browsetable_cli import  browsetable_cli as browsetable
from calstat_cli import  calstat_cli as calstat
from caltabconvert_cli import  caltabconvert_cli as caltabconvert
from clean_cli import  clean_cli as clean
from clearcal_cli import  clearcal_cli as clearcal
from clearstat_cli import  clearstat_cli as clearstat
from concat_cli import  concat_cli as concat
from conjugatevis_cli import  conjugatevis_cli as conjugatevis
from cvel_cli import  cvel_cli as cvel
from cvel2_cli import  cvel2_cli as cvel2
from deconvolve_cli import  deconvolve_cli as deconvolve
from delmod_cli import  delmod_cli as delmod
from exportasdm_cli import  exportasdm_cli as exportasdm
from exportfits_cli import  exportfits_cli as exportfits
from exportuvfits_cli import  exportuvfits_cli as exportuvfits
from feather_cli import  feather_cli as feather
from fixplanets_cli import  fixplanets_cli as fixplanets
from fixvis_cli import  fixvis_cli as fixvis
from flagcmd_cli import  flagcmd_cli as flagcmd
from flagdata_cli import  flagdata_cli as flagdata
from flagmanager_cli import  flagmanager_cli as flagmanager
from fluxscale_cli import  fluxscale_cli as fluxscale
from fringefit_cli import  fringefit_cli as fringefit
from ft_cli import  ft_cli as ft
from gaincal_cli import  gaincal_cli as gaincal
from gencal_cli import  gencal_cli as gencal
from hanningsmooth_cli import  hanningsmooth_cli as hanningsmooth
from imcollapse_cli import  imcollapse_cli as imcollapse
from imcontsub_cli import  imcontsub_cli as imcontsub
from imdev_cli import  imdev_cli as imdev
from imfit_cli import  imfit_cli as imfit
from imhead_cli import  imhead_cli as imhead
from imhistory_cli import  imhistory_cli as imhistory
from immath_cli import  immath_cli as immath
from immoments_cli import  immoments_cli as immoments
from impbcor_cli import  impbcor_cli as impbcor
from importatca_cli import  importatca_cli as importatca
from importasap_cli import  importasap_cli as importasap
from importasdm_cli import  importasdm_cli as importasdm
from importfits_cli import  importfits_cli as importfits
from importfitsidi_cli import  importfitsidi_cli as importfitsidi
from importgmrt_cli import  importgmrt_cli as importgmrt
from importmiriad_cli import  importmiriad_cli as importmiriad
from importnro_cli import  importnro_cli as importnro
from importuvfits_cli import  importuvfits_cli as importuvfits
from importvla_cli import  importvla_cli as importvla
from imrebin_cli import  imrebin_cli as imrebin
from imreframe_cli import  imreframe_cli as imreframe
from imregrid_cli import  imregrid_cli as imregrid
from imsmooth_cli import  imsmooth_cli as imsmooth
from imstat_cli import  imstat_cli as imstat
from imsubimage_cli import  imsubimage_cli as imsubimage
from imtrans_cli import  imtrans_cli as imtrans
from imval_cli import  imval_cli as imval
from imview_cli import  imview_cli as imview
from initweights_cli import  initweights_cli as initweights
from listcal_cli import  listcal_cli as listcal
from listhistory_cli import  listhistory_cli as listhistory
from listfits_cli import  listfits_cli as listfits
from listobs_cli import  listobs_cli as listobs
from listpartition_cli import  listpartition_cli as listpartition
from listsdm_cli import  listsdm_cli as listsdm
from listvis_cli import  listvis_cli as listvis
from makemask_cli import  makemask_cli as makemask
from msview_cli import  msview_cli as msview
from mstransform_cli import  mstransform_cli as mstransform
from msuvbin_cli import  msuvbin_cli as msuvbin
from nrobeamaverage_cli import  nrobeamaverage_cli as nrobeamaverage
from oldsplit_cli import  oldsplit_cli as oldsplit
from plotants_cli import  plotants_cli as plotants
from plotbandpass_cli import  plotbandpass_cli as plotbandpass
from plotcal_cli import  plotcal_cli as plotcal
from plotms_cli import  plotms_cli as plotms
from plotweather_cli import  plotweather_cli as plotweather
from plotprofilemap_cli import  plotprofilemap_cli as plotprofilemap
from partition_cli import  partition_cli as partition
from polcal_cli import  polcal_cli as polcal
from polfromgain_cli import  polfromgain_cli as polfromgain
from predictcomp_cli import  predictcomp_cli as predictcomp
from impv_cli import  impv_cli as impv
from rerefant_cli import  rerefant_cli as rerefant
from rmfit_cli import  rmfit_cli as rmfit
from rmtables_cli import  rmtables_cli as rmtables
from sdbaseline_cli import  sdbaseline_cli as sdbaseline
from sdcal_cli import  sdcal_cli as sdcal
from sdfit_cli import  sdfit_cli as sdfit
from sdfixscan_cli import  sdfixscan_cli as sdfixscan
from sdgaincal_cli import  sdgaincal_cli as sdgaincal
from sdimaging_cli import  sdimaging_cli as sdimaging
from tsdimaging_cli import  tsdimaging_cli as tsdimaging
from sdpolaverage_cli import  sdpolaverage_cli as sdpolaverage
from sdsidebandsplit_cli import  sdsidebandsplit_cli as sdsidebandsplit
from sdsmooth_cli import  sdsmooth_cli as sdsmooth
from setjy_cli import  setjy_cli as setjy
from simalma_cli import  simalma_cli as simalma
from simobserve_cli import  simobserve_cli as simobserve
from simanalyze_cli import  simanalyze_cli as simanalyze
from slsearch_cli import  slsearch_cli as slsearch
from smoothcal_cli import  smoothcal_cli as smoothcal
from specfit_cli import  specfit_cli as specfit
from specflux_cli import  specflux_cli as specflux
from specsmooth_cli import  specsmooth_cli as specsmooth
from splattotable_cli import  splattotable_cli as splattotable
from split_cli import  split_cli as split
from spxfit_cli import  spxfit_cli as spxfit
from oldstatwt_cli import  oldstatwt_cli as oldstatwt
from statwt_cli import  statwt_cli as statwt
from tclean_cli import  tclean_cli as tclean
from tclean2_cli import  tclean2_cli as tclean2
from testconcat_cli import  testconcat_cli as testconcat
from uvcontsub_cli import  uvcontsub_cli as uvcontsub
from uvcontsub3_cli import  uvcontsub3_cli as uvcontsub3
from uvmodelfit_cli import  uvmodelfit_cli as uvmodelfit
from uvsub_cli import  uvsub_cli as uvsub
from viewer_cli import  viewer_cli as viewer
from wvrgcal_cli import  wvrgcal_cli as wvrgcal
from virtualconcat_cli import  virtualconcat_cli as virtualconcat
from vishead_cli import  vishead_cli as vishead
from visstat_cli import  visstat_cli as visstat
from widebandpbcor_cli import  widebandpbcor_cli as widebandpbcor

from split_cli import  split_cli as split2
from hanningsmooth_cli import  hanningsmooth_cli as hanningsmooth2
from tget import *
